// This file is auto-generated by scripts/generate-template-hash.ts
// Do not edit manually. Run "pnpm generate:hash" to regenerate.
export const TEMPLATE_HASH_BY_THEME = {
	default: "96341",
	matrix: "951f8",
	resume: "58588",
} as const;

export function getTemplateHash(theme?: string): string {
	if (!theme) return TEMPLATE_HASH_BY_THEME.default;
	return (
		TEMPLATE_HASH_BY_THEME[theme as keyof typeof TEMPLATE_HASH_BY_THEME] ??
		TEMPLATE_HASH_BY_THEME.default
	);
}
